### ISSUE TITLE
Doesn't build in STM32CubeIDE v1.13.2

### ISSUE THREAD

**Issue by miller-craig** [riverdi/riverdi-eve-lib#1]
../Core/Src/App_Common.c:35:10: fatal error: platform.h: No such file or directory
